# Autogenerated by maintainers/scripts/bootstrap-files/refresh-tarballs.bash as:
# $ ./refresh-tarballs.bash --targets=riscv64-unknown-linux-musl
#
# Metadata:
# - nixpkgs revision: 7d78e04d4d13ce0b5a97ea52d4debf052756c30d
# - hydra build: https://hydra.nixos.org/job/nixpkgs/cross-trunk/bootstrapTools.riscv64-unknown-linux-musl.build/latest
# - resolved hydra build: https://hydra.nixos.org/build/297514186
# - instantiated derivation: /nix/store/spxlsg04m57crnfkgh3fsba2i1ybi7dl-stdenv-bootstrap-tools-riscv64-unknown-linux-musl.drv
# - output directory: /nix/store/n8cgi0w25w04m0p0609d2wbxxc80ac61-stdenv-bootstrap-tools-riscv64-unknown-linux-musl
# - build time: Fri, 16 May 2025 00:58:29 +0000
{
  bootstrapTools = import <nix/fetchurl.nix> {
    url = "http://tarballs.nixos.org/stdenv/riscv64-unknown-linux-musl/7d78e04d4d13ce0b5a97ea52d4debf052756c30d/bootstrap-tools.tar.xz";
    hash = "sha256-XdmmE810gUdB/uQ9/QrLUPBwQnt5s41wjVANdbhjvLs=";
  };
  busybox = import <nix/fetchurl.nix> {
    url = "http://tarballs.nixos.org/stdenv/riscv64-unknown-linux-musl/7d78e04d4d13ce0b5a97ea52d4debf052756c30d/busybox";
    hash = "sha256-NG7u3Cb3GD9uOZDVWZI2jEFyggw4ciwCoxn6qoL2VGs=";
    executable = true;
  };
}
